spring:
  datasource:
    hikari:
      h1:
        username: root
        password: root
        url: jdbc:mysql://192.168.1.11/cd_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
      h2:
        username: root
        password: root
        url: jdbc:mysql://192.168.1.11/mogu_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
      h3:
        username: root
        password: root
        url: jdbc:mysql://192.168.1.11/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
